### ISSUE TITLE
PController Filtering

### ISSUE THREAD

**Issue by JRegimbal** [JRegimbal/ECSE-211#2]
I'm thinking that we might benefit from increasing the frequency of oscillations in addition to some basic filtering of big changes from ping to ping. Thoughts?

**Comment by DestructiveReasoning** [comment]
Yes, I agree. I think we need to tweak that oscillator for sure

via Newton Mailhttps://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.0.89&pv=6.0.1&source=email_footer_2
On Thu, Sep 22, 2016 at 12:01pm, Juliette Regimbal <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm thinking that we might benefit from increasing the frequency of oscillations in addition to some basic filtering of big changes from ping to ping. Thoughts?
